### ISSUE TITLE
How to install license to project

### ISSUE THREAD

**Issue by vrushabhbidari** [uhudpoyraz/FlightTrackApp#1]
I have downloaded new license to the project but I am not able to add that please help me..

**Comment by uhudpoyraz** [comment]
Do you have free trial keys ?

**Comment by vrushabhbidari** [comment]
> Do you have free trial keys ?

Yes I have

**Comment by uhudpoyraz** [comment]
> 
> 
> > Do you have free trial keys ?
> 
> Yes I have
JxBrowser changed the way of licensing. When created this project,only import license.jar but now use license key.
You can follow instructions https://jxbrowser-support.teamdev.com/docs/guides/licensing.html#adding-the-license-to-a-project

**Comment by vrushabhbidari** [comment]
> > > Do you have free trial keys ?
> > 
> > 
> > Yes I have
> 
> You can follow instructions https://jxbrowser-support.teamdev.com/docs/guides/licensing.html#adding-the-license-to-a-project

I have but not able to do.. Can u please make a video or step by step instructions on how to install key in project

**Comment by vrushabhbidari** [comment]
How to provide that key ? Where is that systemproperty?

**Comment by uhudpoyraz** [comment]
change row 53. row in https://github.com/uhudpoyraz/FlightTrackApp/blob/master/src/proje/Map.java
Engine engine = Engine.newInstance(
        EngineOptions.newBuilder(HARDWARE_ACCELERATED)
                .licenseKey("your_license_key")
                .build());
final Browser browser = engine.newBrowser();

try it, i think it will work.

**Comment by vrushabhbidari** [comment]
> change row 53. row in https://github.com/uhudpoyraz/FlightTrackApp/blob/master/src/proje/Map.java
> Engine engine = Engine.newInstance(
> EngineOptions.newBuilder(HARDWARE_ACCELERATED)
> .licenseKey("your_license_key")
> .build());
> final Browser browser = engine.newBrowser();
> 
> try it, i think it will work.

Its showing another error now.. 
Error : Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problems: 
	Engine cannot be resolved to a type
	Engine cannot be resolved
	EngineOptions cannot be resolved
	HARDWARE_ACCELERATED cannot be resolved to a variable

	at proje.Map.initialize(Map.java:53)
	at proje.Map.<init>(Map.java:46)
	at proje.Map$1.run(Map.java:33)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by uhudpoyraz** [comment]
I upgraded jxbrowser from 5.x to 7.x. and fixed above error.But maps not work stabil. A lot of things changed for 6 years.

**Comment by vrushabhbidari** [comment]
> I upgraded jxbrowser from 5.x to 7.x. and fixed above error.But maps not work stabil. A lot of things changed for 6 years.

Sir please help me in executing this project.. I really want this.. Please help me
